In [2]:
import numpy as np

marks = np.array([78, 85, 62, 90, 55, 88, 73, 95, 68, 80])

print("Student Marks:", marks)


total = np.sum(marks)
average = np.mean(marks)
maximum = np.max(marks)
minimum = np.min(marks)

print("Total Marks:", total)
print("Average Marks:", average)
print("Maximum Mark:", maximum)
print("Minimum Mark:", minimum)

Student Marks: [78 85 62 90 55 88 73 95 68 80]
Total Marks: 774
Average Marks: 77.4
Maximum Mark: 95
Minimum Mark: 55

In [3]:


numbers = np.arange(1, 51)

even_numbers = numbers[numbers % 2 == 0]

print("Numbers:", numbers)
print("Even Numbers:", even_numbers)

Numbers: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
Even Numbers: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]

In [4]:



A = np.array([10, 20, 30, 40, 50])
B = np.array([2, 4, 5, 8, 10])


add = A + B
sub = A - B
mul= A * B
div = A / B

print("A:", A)
print("B:", B)

print("Add:", add)
print("Subt:", sub)
print("Mul:", mul)
print("Div:", div)

A: [10 20 30 40 50]
B: [ 2  4  5  8 10]
Add: [12 24 35 48 60]
Subt: [ 8 16 25 32 40]
Mul: [ 20  80 150 320 500]
Div: [5. 5. 6. 5. 5.]

In [5]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Matrix:")
print(matrix)


row = np.sum(matrix, axis=1)
column = np.sum(matrix, axis=0)
max= np.max(matrix)
min = np.min(matrix)

print("Row:", row)
print("Column:", column)
print("Maximum :", max)
print("Minimum :", min)

Matrix:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Row: [ 60 150 240]
Column: [120 150 180]
Maximum : 90
Minimum : 10

In [6]:
numbers = np.random.randint(1, 101, 20)

greater_than_50 = numbers[numbers > 50]
less_than_25 = numbers[numbers < 25]

print( numbers)
print( greater_than_50)
print( less_than_25)

[38 59 41 22 19 27 46 62 60 12 59 25 59 47 53 72 23  3 67 40]
[59 62 60 59 59 53 72 67]
[22 19 12 23  3]

In [7]:



marks = np.array([
    [80, 75, 90],
    [65, 70, 60],
    [95, 85, 88],
    [50, 55, 65],
    [78, 82, 76]
])

print("Student Marks:")
print(marks)


total = np.sum(marks, axis=1)

average = np.mean(marks, axis=1)
highest = np.max(marks, axis=0)
lowest = np.min(marks, axis=0)

print( total)
print( average)
print( highest)
print(lowest)

Student Marks:
[[80 75 90]
 [65 70 60]
 [95 85 88]
 [50 55 65]
 [78 82 76]]
[245 195 268 170 236]
[81.66666667 65.         89.33333333 56.66666667 78.66666667]
[95 85 90]
[50 55 60]

In [8]:

salary = np.array([30000, 40000, 50000, 60000, 70000])

new_salary = salary + (salary * 0.10)

print(salary)
print(new_salary)

[30000 40000 50000 60000 70000]
[33000. 44000. 55000. 66000. 77000.]

In [9]:

temperature = np.array([32, 35, 31, 38, 36, 30, 34])

highest = np.max(temperature)
lowest = np.min(temperature)
average = np.mean(temperature)

above_average = temperature[temperature > average]

print(temperature)
print( highest)
print(lowest)
print(average)
print( above_average)

[32 35 31 38 36 30 34]
38
30
33.714285714285715
[35 38 36 34]

In [10]:

numbers = np.arange(1, 101)


even_numbers = numbers[numbers % 2 == 0]
odd_numbers = numbers[numbers % 2 != 0]
divisible_by_5 = numbers[numbers % 5 == 0]
divisible_by_10 = numbers[numbers % 10 == 0]

print( numbers)
print(even_numbers)
print(odd_numbers)
print(divisible_by_5)
print( divisible_by_10)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]
[ 10  20  30  40  50  60  70  80  90 100]

In [11]:

marks = np.random.randint(0, 101, 10)

print("Original Marks:", marks)

marks[marks < 40] = 40

print("Updated Marks:", marks)

Original Marks: [99 13 55 59 55 19 44 49  3 43]
Updated Marks: [99 40 55 59 55 40 44 49 40 43]

section -2

In [12]:
matrix = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])

print(matrix)
transpose = matrix.T
row_sum = np.sum(matrix, axis=1)
column_sum = np.sum(matrix, axis=0)
diagonal = np.diag(matrix)
print(transpose)
print(row_sum)
print(column_sum)
print(diagonal)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]
[[ 10  50  90 130]
 [ 20  60 100 140]
 [ 30  70 110 150]
 [ 40  80 120 160]]
[100 260 420 580]
[280 320 360 400]
[ 10  60 110 160]

In [13]:

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])


addition = A + B
subtraction = A - B
multiplication = A * B

print(A)

print(B)

print(addition)

print(subtraction)


print(multiplication)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]

In [14]:

marks = np.array([
    65, 78, 82, 90, 55,
    72, 88, 60, 95, 70,
    84, 76, 68, 91, 58,
    80, 74, 86, 62, 79
])

mean = np.mean(marks)
median = np.median(marks)
std = np.std(marks)
variance = np.var(marks)

print( marks)

print(mean)
print( median)
print( std)
print(variance)

[65 78 82 90 55 72 88 60 95 70 84 76 68 91 58 80 74 86 62 79]
75.65
77.0
11.424863237693481
130.52749999999997

In [15]:

salary = np.array([
    25000, 32000, 45000, 55000,
    28000, 60000, 75000, 40000,
    52000, 22000
])

greater_50k = salary[salary > 50000]
less_30k = salary[salary < 30000]

between_30k_60k = salary[
    (salary >= 30000) & (salary <= 60000)
]

print( salary)

print(greater_50k)
print(less_30k)
print(between_30k_60k)

[25000 32000 45000 55000 28000 60000 75000 40000 52000 22000]
[55000 60000 75000 52000]
[25000 28000 22000]
[32000 45000 55000 60000 40000 52000]

In [16]:

numbers = np.array([45, 12, 89, 34, 67, 23, 90, 56, 10, 78])
ascending = np.sort(numbers)
descending = np.sort(numbers)[::-1]

print( numbers)
print(ascending)
print(descending)

[45 12 89 34 67 23 90 56 10 78]
[10 12 23 34 45 56 67 78 89 90]
[90 89 78 67 56 45 34 23 12 10]

section 3

In [17]:
import pandas as pd

data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["yash", "babu", "keerthivasan", "rinthiya", "joel"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "Java", "Data Science", "Python", "Java"],
    "Mark": [85, 72, 91, 45, 68]
}

df = pd.DataFrame(data)
print(df)

   Student_ID          Name  Age        Course  Mark
0         101          yash   20        Python    85
1         102          babu   21          Java    72
2         103  keerthivasan   19  Data Science    91
3         104      rinthiya   22        Python    45
4         105          joel   20          Java    68

In [18]:

data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["yash", "babu", "keerthivasan", "rinthiya", "joel"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "Java", "Data Science", "Python", "Java"],
    "Mark": [85, 72, 91, 45, 68]
}
df = pd.DataFrame(data)
print(df[["Name", "Mark"]])

           Name  Mark
0          yash    85
1          babu    72
2  keerthivasan    91
3      rinthiya    45
4          joel    68

In [19]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["yash", "babu", "keerthivasan", "rinthiya", "joel"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "Java", "Data Science", "Python", "Java"],
    "Mark": [85, 72, 91, 45, 68]
}
df = pd.DataFrame(data)
df= df[df["Mark"] > 70]
df

   Student_ID          Name  Age        Course  Mark
0         101          yash   20        Python    85
1         102          babu   21          Java    72
2         103  keerthivasan   19  Data Science    91

In [20]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["yash", "babu", "keerthivasan", "rinthiya", "joel"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "Java", "Data Science", "Python", "Java"],
    "Mark": [85, 72, 91, 45, 68]
}
df = pd.DataFrame(data)
df= df[df["Mark"] < 50]
df

   Student_ID      Name  Age  Course  Mark
3         104  rinthiya   22  Python    45

In [21]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["yash", "babu", "keerthivasan", "rinthiya", "joel"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "Java", "Data Science", "Python", "Java"],
    "Mark": [85, 72, 91, 45, 68]
}
df = pd.DataFrame(data)
highest_to_lowest = df.sort_values(by="Mark", ascending=False)
lowest_to_highest = df.sort_values(by="Mark", ascending=True)
print(highest_to_lowest)
print(lowest_to_highest)

   Student_ID          Name  Age        Course  Mark
2         103  keerthivasan   19  Data Science    91
0         101          yash   20        Python    85
1         102          babu   21          Java    72
4         105          joel   20          Java    68
3         104      rinthiya   22        Python    45
   Student_ID          Name  Age        Course  Mark
3         104      rinthiya   22        Python    45
4         105          joel   20          Java    68
1         102          babu   21          Java    72
0         101          yash   20        Python    85
2         103  keerthivasan   19  Data Science    91

In [22]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["yash", "babu", "keerthivasan", "rinthiya", "joel"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "Java", "Data Science", "Python", "Java"],
    "Mark": [85, 72, 91, 45, 68]
}
df = pd.DataFrame(data)
ave= df["Mark"].mean()
max = df["Mark"].max()
min = df["Mark"].min()
total= df["Mark"].sum()

print( ave)
print(max)
print(min)
print(total)

72.2
91
45
361

In [23]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["yash", "babu", "keerthivasan", "rinthiya", "joel"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "Java", "Data Science", "Python", "Java"],
    "Mark": [85, 72, 91, 45, 68]
}
df = pd.DataFrame(data)
df["Result"] = np.where(df["Mark"] >= 50, "PASS", "FAIL")
print(df)

   Student_ID          Name  Age        Course  Mark Result
0         101          yash   20        Python    85   PASS
1         102          babu   21          Java    72   PASS
2         103  keerthivasan   19  Data Science    91   PASS
3         104      rinthiya   22        Python    45   FAIL
4         105          joel   20          Java    68   PASS

In [24]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["yash", "babu", "keerthivasan", "rinthiya", "joel"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "Java", "Data Science", "Python", "Java"],
    "Mark": [85, 72, 91, 45, 68]
}
df = pd.DataFrame(data)
def calculate_grade(mark):
    if mark >= 90:
        return "A"
    elif mark >= 70:
        return "B"
    elif mark >= 50:
        return "C"
    else:
        return "D"
df["Grade"] = df["Mark"].apply(calculate_grade)
print(df)

   Student_ID          Name  Age        Course  Mark Grade
0         101          yash   20        Python    85     B
1         102          babu   21          Java    72     B
2         103  keerthivasan   19  Data Science    91     A
3         104      rinthiya   22        Python    45     D
4         105          joel   20          Java    68     C

In [25]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["yash", "babu", "keerthivasan", "rinthiya", "joel"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "Java", "Data Science", "Python", "Java"],
    "Mark": [85, 72, 91, 45, 68]
}
df = pd.DataFrame(data)
df = df.nlargest(3, "Mark")
df

   Student_ID          Name  Age        Course  Mark
2         103  keerthivasan   19  Data Science    91
0         101          yash   20        Python    85
1         102          babu   21          Java    72

section 4

In [26]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["yash", "babu", "keerthivasan", "rinthiya", "joel"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "Java", "Data Science", "Python", "Java"],
    "Mark": [85, 72, 91, 45, 68]
}
df = pd.DataFrame(data)
df["Result"] = np.where(df["Mark"] >= 50, "PASS", "FAIL")
passed = (df["Result"] == "PASS").sum()
failed = (df["Result"] == "FAIL").sum()
print(passed)
print(failed)

4
1

In [27]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["yash", "babu", "keerthivasan", "rinthiya", "joel"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "Java", "Data Science", "Python", "Java"],
    "Mark": [85, 72, 91, 45, 68]
}
df = pd.DataFrame(data)
df = df.groupby("Course").size()
df

Course
Data Science    1
Java            2
Python          2
dtype: int64

In [28]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["yash", "babu", "keerthivasan", "rinthiya", "joel"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "Java", "Data Science", "Python", "Java"],
    "Mark": [85, 72, 91, 45, 68]
}
df = pd.DataFrame(data)
df= df.groupby("Course")["Mark"].mean()
df

Course
Data Science    91.0
Java            70.0
Python          65.0
Name: Mark, dtype: float64

In [29]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["yash", "babu", "keerthivasan", "rinthiya", "joel"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "Java", "Data Science", "Python", "Java"],
    "Mark": [85, 72, 91, 45, 68]
}
df = pd.DataFrame(data)
df = df.groupby("Course")["Mark"].max()
df

Course
Data Science    91
Java            72
Python          85
Name: Mark, dtype: int64

In [30]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["yash", "babu", "keerthivasan", "rinthiya", "joel"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "Java", "Data Science", "Python", "Java"],
    "Mark": [85, 72, 91, 45, 68]
}
df = pd.DataFrame(data)
df = df[(df["Age"] > 20) & (df["Mark"] > 75)]
df

Empty DataFrame
Columns: [Student_ID, Name, Age, Course, Mark]
Index: []

In [31]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["yash", "babu", "keerthivasan", "rinthiya", "joel"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "Java", "Data Science", "Python", "Java"],
    "Mark": [85, 72, 91, 45, 68]
}
df = pd.DataFrame(data)
def get_status(mark):
    if mark >= 80:
        return "Excellent"
    elif mark >= 60:
        return "Good"
    elif mark >= 50:
        return "Average"
    else:
        return "Poor"

df["Status"] = df["Mark"].apply(get_status)
df

   Student_ID          Name  Age        Course  Mark     Status
0         101          yash   20        Python    85  Excellent
1         102          babu   21          Java    72       Good
2         103  keerthivasan   19  Data Science    91  Excellent
3         104      rinthiya   22        Python    45       Poor
4         105          joel   20          Java    68       Good

In [32]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["yash", "babu", "keerthivasan", "rinthiya", "joel"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "Java", "Data Science", "Python", "Java"],
    "Mark": [85, 72, 91, 45, 68]
}
df = pd.DataFrame(data)
df = df.loc[df["Mark"].idxmax()]
df

Student_ID             103
Name          keerthivasan
Age                     19
Course        Data Science
Mark                    91
Name: 2, dtype: object

In [33]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["yash", "babu", "keerthivasan", "rinthiya", "joel"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "Java", "Data Science", "Python", "Java"],
    "Mark": [85, 72, 91, 45, 68]
}
df = pd.DataFrame(data)
df = df.loc[df["Mark"].idxmax()]
df

Student_ID             103
Name          keerthivasan
Age                     19
Course        Data Science
Mark                    91
Name: 2, dtype: object

In [34]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["yash", "babu", "keerthivasan", "rinthiya", "joel"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "Java", "Data Science", "Python", "Java"],
    "Mark": [85, 72, 91, 45, 68]
}
df = pd.DataFrame(data)
df = df.loc[df["Mark"].idxmin()]
df

Student_ID         104
Name          rinthiya
Age                 22
Course          Python
Mark                45
Name: 3, dtype: object

In [35]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["yash", "babu", "keerthivasan", "rinthiya", "joel"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "Java", "Data Science", "Python", "Java"],
    "Mark": [85, 72, 91, 45, 68]
}
df = pd.DataFrame(data)
df =  df.groupby("Course")["Mark"].mean()
df

Course
Data Science    91.0
Java            70.0
Python          65.0
Name: Mark, dtype: float64

In [36]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["yash", "babu", "keerthivasan", "rinthiya", "joel"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "Java", "Data Science", "Python", "Java"],
    "Mark": [85, 72, 91, 45, 68]
}
df = pd.DataFrame(data)
def get_grade(mark):
    if mark >= 80:
        return "A"
    elif mark >= 60:
        return "B"
    elif mark >= 50:
        return "C"
    else:
        return "D"

df["Grade"] = df["Mark"].apply(get_grade)
df = df["Grade"].value_counts()
df

Grade
A    2
B    2
D    1
Name: count, dtype: int64

In [41]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["yash", "babu", "keerthivasan", "rinthiya", "joel"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "Java", "Data Science", "Python", "Java"],
    "Mark": [85, 72, 91, 45, 68]
}
df = pd.DataFrame(data)
df.to_csv("students.csv", index=False)

In [42]:
df = pd.read_csv(r"C:\Users\yasht\OneDrive\my career\internship\students.csv")
df

   Student_ID          Name  Age        Course  Mark
0         101          yash   20        Python    85
1         102          babu   21          Java    72
2         103  keerthivasan   19  Data Science    91
3         104      rinthiya   22        Python    45
4         105          joel   20          Java    68

section 5

In [44]:
import pandas as pd

data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Yash", "Babu", "Keerthivasan", "Rinthiya", "Joel"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Experience": [3, 6, 8, 4, 7],
    "Salary": [45000, 55000, 75000, 48000, 65000]
}
df = pd.DataFrame(data)
df.to_csv("employees.csv", index=False)
df =  pd.read_csv(r"C:\Users\yasht\OneDrive\my career\internship\employees.csv")
df

   Employee_ID          Name Department  Experience  Salary
0          101          Yash         IT           3   45000
1          102          Babu         HR           6   55000
2          103  Keerthivasan         IT           8   75000
3          104      Rinthiya    Finance           4   48000
4          105          Joel         HR           7   65000

In [50]:
import pandas as pd
df =  pd.read_csv(r"C:\Users\yasht\OneDrive\my career\internship\employees.csv")
df= df[df["Salary"] > 50000]
df

   Employee_ID          Name Department  Experience  Salary
1          102          Babu         HR           6   55000
2          103  Keerthivasan         IT           8   75000
4          105          Joel         HR           7   65000

In [53]:
df =  pd.read_csv(r"C:\Users\yasht\OneDrive\my career\internship\employees.csv")
df = df.loc[df["Salary"].idxmax()]
df

Employee_ID             103
Name           Keerthivasan
Department               IT
Experience                8
Salary                75000
Name: 2, dtype: object

In [54]:
df =  pd.read_csv(r"C:\Users\yasht\OneDrive\my career\internship\employees.csv")
df = df.loc[df["Salary"].idxmin()]
df

Employee_ID      101
Name            Yash
Department        IT
Experience         3
Salary         45000
Name: 0, dtype: object

In [55]:
df =  pd.read_csv(r"C:\Users\yasht\OneDrive\my career\internship\employees.csv")
df = df["Salary"].mean()
df

57600.0

In [56]:
df =  pd.read_csv(r"C:\Users\yasht\OneDrive\my career\internship\employees.csv")
department_avg = df.groupby("Department")["Salary"].mean()
print(department_avg)

Department
Finance    48000.0
HR         60000.0
IT         60000.0
Name: Salary, dtype: float64

In [57]:
df =  pd.read_csv(r"C:\Users\yasht\OneDrive\my career\internship\employees.csv")
df = df.sort_values(by="Salary")
df

   Employee_ID          Name Department  Experience  Salary
0          101          Yash         IT           3   45000
3          104      Rinthiya    Finance           4   48000
1          102          Babu         HR           6   55000
4          105          Joel         HR           7   65000
2          103  Keerthivasan         IT           8   75000

In [58]:
df =  pd.read_csv(r"C:\Users\yasht\OneDrive\my career\internship\employees.csv")
df["New_Salary"] = df["Salary"] * 1.10
df

   Employee_ID          Name Department  Experience  Salary  New_Salary
0          101          Yash         IT           3   45000     49500.0
1          102          Babu         HR           6   55000     60500.0
2          103  Keerthivasan         IT           8   75000     82500.0
3          104      Rinthiya    Finance           4   48000     52800.0
4          105          Joel         HR           7   65000     71500.0

In [59]:
df.to_csv("employee_salary_report.csv", index=False)

section 6

Employee Salary Analysis System.

In [63]:
import pandas as pd

data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Yash", "Babu", "Keerthivasan", "Rinthiya", "Joel"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Experience": [3, 6, 8, 4, 7],
    "Salary": [45000, 55000, 75000, 48000, 65000]
}

employee_df = pd.DataFrame(data)
print("1. All Employees:")
print(employee_df)
print("\n2. Highest Salary:")
print(employee_df.loc[employee_df["Salary"].idxmax()])

print("\n3. Lowest Salary:")
print(employee_df.loc[employee_df["Salary"].idxmin()])

average_salary = employee_df["Salary"].mean()

print(average_salary)
print(employee_df[employee_df["Salary"] > 50000])
print(employee_df[employee_df["Experience"] > 5])

print(employee_df["Department"].value_counts())
print(employee_df.groupby("Department")["Salary"].mean())
sorted_df = employee_df.sort_values(
    by="Salary",
    ascending=False
)

print(sorted_df)

employee_df["New_Salary"] = employee_df["Salary"] * 1.10

print("\n10. Salary after 10% increment:")
print(employee_df)
df.to_csv(
    "employee_salary_report.csv1",
    index=False
)

1. All Employees:
   Employee_ID          Name Department  Experience  Salary
0          101          Yash         IT           3   45000
1          102          Babu         HR           6   55000
2          103  Keerthivasan         IT           8   75000
3          104      Rinthiya    Finance           4   48000
4          105          Joel         HR           7   65000

2. Highest Salary:
Employee_ID             103
Name           Keerthivasan
Department               IT
Experience                8
Salary                75000
Name: 2, dtype: object

3. Lowest Salary:
Employee_ID      101
Name            Yash
Department        IT
Experience         3
Salary         45000
Name: 0, dtype: object
57600.0
   Employee_ID          Name Department  Experience  Salary
1          102          Babu         HR           6   55000
2          103  Keerthivasan         IT           8   75000
4          105          Joel         HR           7   65000
   Employee_ID          Name Department  Experience  Salary
1          102          Babu         HR           6   55000
2          103  Keerthivasan         IT           8   75000
4          105          Joel         HR           7   65000
Department
IT         2
HR         2
Finance    1
Name: count, dtype: int64
Department
Finance    48000.0
HR         60000.0
IT         60000.0
Name: Salary, dtype: float64
   Employee_ID          Name Department  Experience  Salary
2          103  Keerthivasan         IT           8   75000
4          105          Joel         HR           7   65000
1          102          Babu         HR           6   55000
3          104      Rinthiya    Finance           4   48000
0          101          Yash         IT           3   45000

10. Salary after 10% increment:
   Employee_ID          Name Department  Experience  Salary  New_Salary
0          101          Yash         IT           3   45000     49500.0
1          102          Babu         HR           6   55000     60500.0
2          103  Keerthivasan         IT           8   75000     82500.0
3          104      Rinthiya    Finance           4   48000     52800.0
4          105          Joel         HR           7   65000     71500.0

section 7

Supermarket Sales Analysis System

In [66]:
import pandas as pd

data = {
    "Bill_No": [1001, 1002, 1003, 1004, 1005, 1006],
    "Product": ["Rice", "Oil", "Milk", "Rice", "Soap", "Oil"],
    "Category": ["Grocery", "Grocery", "Dairy", "Grocery", "Personal Care", "Grocery"],
    "Quantity": [50, 20, 40, 30, 60, 25],
    "Price": [1200, 1800, 60, 1200, 50, 1800]
}

df = pd.DataFrame(data)
df["Total"] = df["Quantity"] * df["Price"]

print(" Data with Total:")
print(df)

total_sales = df["Total"].sum()

print("\nTotal Sales:")
print(total_sales)

print("\n Highest Sale:")
print(df.loc[df["Total"].idxmax()])

print("\nLowest Sale:")
print(df.loc[df["Total"].idxmin()])

average_sale = df["Total"].mean()

print("\n Average Sale:")
print(average_sale)

category_sales = df.groupby("Category")["Total"].sum()

print("\nCategory-wise Sales:")
print(category_sales)


product_sales = df.groupby("Product")["Total"].sum()

print("\n7. Product-wise Sales:")
print(product_sales)
best_product = product_sales.idxmax()

print("\nBest-selling Product:")
print(best_product)

above_10000 = product_sales[product_sales > 10000]

print("\n Products with sales above 10000:")
print(above_10000)

sorted_products = product_sales.sort_values(ascending=False)

print("\n Products sorted by Total Sales:")
print(sorted_products)

df.to_csv("supermarket_sales_report.csv", index=False)

 Data with Total:
   Bill_No Product       Category  Quantity  Price  Total
0     1001    Rice        Grocery        50   1200  60000
1     1002     Oil        Grocery        20   1800  36000
2     1003    Milk          Dairy        40     60   2400
3     1004    Rice        Grocery        30   1200  36000
4     1005    Soap  Personal Care        60     50   3000
5     1006     Oil        Grocery        25   1800  45000

Total Sales:
182400

 Highest Sale:
Bill_No        1001
Product        Rice
Category    Grocery
Quantity         50
Price          1200
Total         60000
Name: 0, dtype: object

Lowest Sale:
Bill_No      1003
Product      Milk
Category    Dairy
Quantity       40
Price          60
Total        2400
Name: 2, dtype: object

 Average Sale:
30400.0

Category-wise Sales:
Category
Dairy              2400
Grocery          177000
Personal Care      3000
Name: Total, dtype: int64

7. Product-wise Sales:
Product
Milk     2400
Oil     81000
Rice    96000
Soap     3000
Name: Total, dtype: int64

Best-selling Product:
Rice

 Products with sales above 10000:
Product
Oil     81000
Rice    96000
Name: Total, dtype: int64

 Products sorted by Total Sales:
Product
Rice    96000
Oil     81000
Soap     3000
Milk     2400
Name: Total, dtype: int64

section 8

Student Attendance Analysis System

In [ ]:
import pandas as pd

c
df["Attendance"] = (
    df["Present_Days"] / df["Total_Days"]
) * 100

print("Student Attendance Data:")
print(df)

average_attendance = df["Attendance"].mean()

print("\n1. Average Attendance:")
print(average_attendance)

print("\n2. Highest Attendance:")
print(df.loc[df["Attendance"].idxmax()])

print("\n3. Lowest Attendance:")
print(df.loc[df["Attendance"].idxmin()])


below_75 = df[df["Attendance"] < 75]

print("\n4. Students below 75%:")
print(below_75)

above_90 = df[df["Attendance"] > 90]

print("\n5. Students above 90%:")
print(above_90)

df["Eligible"] = df["Attendance"].apply(
    lambda x: "Yes" if x >= 75 else "No"
)

print("\n6. Eligibility:")
print(df)

eligible_count = (df["Eligible"] == "Yes").sum()

print("\n7. Eligible Students:")
print(eligible_count)

non_eligible_count = (df["Eligible"] == "No").sum()

print("\n8. Non-Eligible Students:")
print(non_eligible_count)


sorted_df = df.sort_values(
    by="Attendance",
    ascending=False
)

print("\n9. Students sorted by Attendance:")
print(sorted_df)

df.to_csv(
    "student_attendance_report.csv",
    index=False
)

print("\n10. Report exported successfully.")

Student Attendance Data:
   Student_ID          Name        Course  Total_Days  Present_Days  \
0         101          Yash        Python         100            92
1         102          Babu          Java         100            78
2         103  Keerthivasan  Data Science         100            96
3         104      Rinthiya        Python         100            65
4         105          Joel          Java         100            85
5         106          Arun  Data Science         100            72

   Attendance
0        92.0
1        78.0
2        96.0
3        65.0
4        85.0
5        72.0

1. Average Attendance:
81.33333333333333

2. Highest Attendance:
Student_ID               103
Name            Keerthivasan
Course          Data Science
Total_Days               100
Present_Days              96
Attendance              96.0
Name: 2, dtype: object

3. Lowest Attendance:
Student_ID           104
Name            Rinthiya
Course            Python
Total_Days           100
Present_Days          65
Attendance          65.0
Name: 3, dtype: object

4. Students below 75%:
   Student_ID      Name        Course  Total_Days  Present_Days  Attendance
3         104  Rinthiya        Python         100            65        65.0
5         106      Arun  Data Science         100            72        72.0

5. Students above 90%:
   Student_ID          Name        Course  Total_Days  Present_Days  \
0         101          Yash        Python         100            92
2         103  Keerthivasan  Data Science         100            96

   Attendance
0        92.0
2        96.0

6. Eligibility:
   Student_ID          Name        Course  Total_Days  Present_Days  \
0         101          Yash        Python         100            92
1         102          Babu          Java         100            78
2         103  Keerthivasan  Data Science         100            96
3         104      Rinthiya        Python         100            65
4         105          Joel          Java         100            85
5         106          Arun  Data Science         100            72

   Attendance Eligible
0        92.0      Yes
1        78.0      Yes
2        96.0      Yes
3        65.0       No
4        85.0      Yes
5        72.0       No

7. Eligible Students:
4

8. Non-Eligible Students:
2

9. Students sorted by Attendance:
   Student_ID          Name        Course  Total_Days  Present_Days  \
2         103  Keerthivasan  Data Science         100            96
0         101          Yash        Python         100            92
4         105          Joel          Java         100            85
1         102          Babu          Java         100            78
5         106          Arun  Data Science         100            72
3         104      Rinthiya        Python         100            65

   Attendance Eligible
2        96.0      Yes
0        92.0      Yes
4        85.0      Yes
1        78.0      Yes
5        72.0       No
3        65.0       No

10. Report exported successfully.

section 9

Student Performance Analysis

In [68]:
import pandas as pd

data = {
    "Name": ["Yash", "Babu", "Keerthi", "Rinthiya", "Joel"],
    "Python": [85, 70, 90, 45, 65],
    "Java": [80, 75, 88, 50, 70],
    "SQL": [90, 65, 95, 55, 75],
    "ML": [88, 72, 92, 40, 68]
}

df = pd.DataFrame(data)

subjects = ["Python", "Java", "SQL", "ML"]
df["Total"] = df[subjects].sum(axis=1)
df["Average"] = df[subjects].mean(axis=1)

print("Highest:", df["Total"].max())
print("Lowest:", df["Total"].min())

df["Result"] = df[subjects].apply(
    lambda x: "Pass" if (x >= 50).all() else "Fail", axis=1
)

df["Grade"] = df["Average"].apply(
    lambda x: "A" if x >= 80 else "B" if x >= 60 else "C" if x >= 50 else "F"
)

print("Top 3:")
print(df.nlargest(3, "Total"))

print("Bottom 3:")
print(df.nsmallest(3, "Total"))
print("Subject Average:\n", df[subjects].mean())
print("Subject Highest:\n", df[subjects].max())
print("Subject Lowest:\n", df[subjects].min())

print("Pass %:", (df["Result"] == "Pass").mean() * 100)

df = df.sort_values("Total", ascending=False)

df.to_csv("student_performance.csv", index=False)

print(df)

Highest: 365
Lowest: 190
Top 3:
      Name  Python  Java  SQL  ML  Total  Average Result Grade
2  Keerthi      90    88   95  92    365    91.25   Pass     A
0     Yash      85    80   90  88    343    85.75   Pass     A
1     Babu      70    75   65  72    282    70.50   Pass     B
Bottom 3:
       Name  Python  Java  SQL  ML  Total  Average Result Grade
3  Rinthiya      45    50   55  40    190     47.5   Fail     F
4      Joel      65    70   75  68    278     69.5   Pass     B
1      Babu      70    75   65  72    282     70.5   Pass     B
Subject Average:
 Python    71.0
Java      72.6
SQL       76.0
ML        72.0
dtype: float64
Subject Highest:
 Python    90
Java      88
SQL       95
ML        92
dtype: int64
Subject Lowest:
 Python    45
Java      50
SQL       55
ML        40
dtype: int64
Pass %: 80.0
       Name  Python  Java  SQL  ML  Total  Average Result Grade
2   Keerthi      90    88   95  92    365    91.25   Pass     A
0      Yash      85    80   90  88    343    85.75   Pass     A
1      Babu      70    75   65  72    282    70.50   Pass     B
4      Joel      65    70   75  68    278    69.50   Pass     B
3  Rinthiya      45    50   55  40    190    47.50   Fail     F

sales data analysis

In [1]:
import pandas as pd

data = {
    "Order_ID": range(1, 51),
    "Date": pd.date_range("2026-01-01", periods=50),
    "Product": ["Laptop", "Phone", "Mouse", "Keyboard", "Monitor"] * 10,
    "Category": ["Electronics", "Electronics", "Accessories", "Accessories", "Electronics"] * 10,
    "City": ["Chennai", "Bangalore", "Mumbai", "Delhi", "Hyderabad"] * 10,
    "Quantity": [10, 20, 50, 30, 15] * 10,
    "Price": [50000, 25000, 500, 1500, 12000] * 10
}

df = pd.DataFrame(data)


df["Revenue"] = df["Quantity"] * df["Price"]


print("Total Revenue:", df["Revenue"].sum())
print("Average Order:", df["Revenue"].mean())
print("Highest Order:\n", df.loc[df["Revenue"].idxmax()])
print("Lowest Order:\n", df.loc[df["Revenue"].idxmin()])


print("City Revenue:\n", df.groupby("City")["Revenue"].sum())
print("Category Revenue:\n", df.groupby("Category")["Revenue"].sum())
print("Product Revenue:\n", df.groupby("Product")["Revenue"].sum())


print("Best Selling Product:",
      df.groupby("Product")["Quantity"].sum().idxmax())


print("Highest Revenue City:",
      df.groupby("City")["Revenue"].sum().idxmax())


print("Top 5 Orders:\n", df.nlargest(5, "Revenue"))


print("Products Quantity > 100:\n",
      df.groupby("Product")["Quantity"].sum()
        [lambda x: x > 100])


df = df.sort_values("Revenue", ascending=False)


df.to_csv("sales_report.csv", index=False)

print(df)

Total Revenue: 12500000
Average Order: 250000.0
Highest Order:
 Order_ID                      1
Date        2026-01-01 00:00:00
Product                  Laptop
Category            Electronics
City                    Chennai
Quantity                     10
Price                     50000
Revenue                  500000
Name: 0, dtype: object
Lowest Order:
 Order_ID                      3
Date        2026-01-03 00:00:00
Product                   Mouse
Category            Accessories
City                     Mumbai
Quantity                     50
Price                       500
Revenue                   25000
Name: 2, dtype: object
City Revenue:
 City
Bangalore    5000000
Chennai      5000000
Delhi         450000
Hyderabad    1800000
Mumbai        250000
Name: Revenue, dtype: int64
Category Revenue:
 Category
Accessories      700000
Electronics    11800000
Name: Revenue, dtype: int64
Product Revenue:
 Product
Keyboard     450000
Laptop      5000000
Monitor     1800000
Mouse        250000
Phone       5000000
Name: Revenue, dtype: int64
Best Selling Product: Mouse
Highest Revenue City: Bangalore
Top 5 Orders:
     Order_ID       Date Product     Category       City  Quantity  Price  \
0          1 2026-01-01  Laptop  Electronics    Chennai        10  50000
1          2 2026-01-02   Phone  Electronics  Bangalore        20  25000
5          6 2026-01-06  Laptop  Electronics    Chennai        10  50000
6          7 2026-01-07   Phone  Electronics  Bangalore        20  25000
10        11 2026-01-11  Laptop  Electronics    Chennai        10  50000

    Revenue
0    500000
1    500000
5    500000
6    500000
10   500000
Products Quantity > 100:
 Product
Keyboard    300
Monitor     150
Mouse       500
Phone       200
Name: Quantity, dtype: int64
    Order_ID       Date   Product     Category       City  Quantity  Price  \
0          1 2026-01-01    Laptop  Electronics    Chennai        10  50000
15        16 2026-01-16    Laptop  Electronics    Chennai        10  50000
46        47 2026-02-16     Phone  Electronics  Bangalore        20  25000
45        46 2026-02-15    Laptop  Electronics    Chennai        10  50000
41        42 2026-02-11     Phone  Electronics  Bangalore        20  25000
40        41 2026-02-10    Laptop  Electronics    Chennai        10  50000
36        37 2026-02-06     Phone  Electronics  Bangalore        20  25000
35        36 2026-02-05    Laptop  Electronics    Chennai        10  50000
31        32 2026-02-01     Phone  Electronics  Bangalore        20  25000
30        31 2026-01-31    Laptop  Electronics    Chennai        10  50000
26        27 2026-01-27     Phone  Electronics  Bangalore        20  25000
1          2 2026-01-02     Phone  Electronics  Bangalore        20  25000
21        22 2026-01-22     Phone  Electronics  Bangalore        20  25000
20        21 2026-01-21    Laptop  Electronics    Chennai        10  50000
16        17 2026-01-17     Phone  Electronics  Bangalore        20  25000
25        26 2026-01-26    Laptop  Electronics    Chennai        10  50000
5          6 2026-01-06    Laptop  Electronics    Chennai        10  50000
6          7 2026-01-07     Phone  Electronics  Bangalore        20  25000
11        12 2026-01-12     Phone  Electronics  Bangalore        20  25000
10        11 2026-01-11    Laptop  Electronics    Chennai        10  50000
14        15 2026-01-15   Monitor  Electronics  Hyderabad        15  12000
29        30 2026-01-30   Monitor  Electronics  Hyderabad        15  12000
44        45 2026-02-14   Monitor  Electronics  Hyderabad        15  12000
4          5 2026-01-05   Monitor  Electronics  Hyderabad        15  12000
39        40 2026-02-09   Monitor  Electronics  Hyderabad        15  12000
34        35 2026-02-04   Monitor  Electronics  Hyderabad        15  12000
9         10 2026-01-10   Monitor  Electronics  Hyderabad        15  12000
49        50 2026-02-19   Monitor  Electronics  Hyderabad        15  12000
24        25 2026-01-25   Monitor  Electronics  Hyderabad        15  12000
19        20 2026-01-20   Monitor  Electronics  Hyderabad        15  12000
28        29 2026-01-29  Keyboard  Accessories      Delhi        30   1500
38        39 2026-02-08  Keyboard  Accessories      Delhi        30   1500
48        49 2026-02-18  Keyboard  Accessories      Delhi        30   1500
3          4 2026-01-04  Keyboard  Accessories      Delhi        30   1500
18        19 2026-01-19  Keyboard  Accessories      Delhi        30   1500
43        44 2026-02-13  Keyboard  Accessories      Delhi        30   1500
13        14 2026-01-14  Keyboard  Accessories      Delhi        30   1500
33        34 2026-02-03  Keyboard  Accessories      Delhi        30   1500
23        24 2026-01-24  Keyboard  Accessories      Delhi        30   1500
8          9 2026-01-09  Keyboard  Accessories      Delhi        30   1500
37        38 2026-02-07     Mouse  Accessories     Mumbai        50    500
27        28 2026-01-28     Mouse  Accessories     Mumbai        50    500
22        23 2026-01-23     Mouse  Accessories     Mumbai        50    500
7          8 2026-01-08     Mouse  Accessories     Mumbai        50    500
42        43 2026-02-12     Mouse  Accessories     Mumbai        50    500
17        18 2026-01-18     Mouse  Accessories     Mumbai        50    500
32        33 2026-02-02     Mouse  Accessories     Mumbai        50    500
2          3 2026-01-03     Mouse  Accessories     Mumbai        50    500
47        48 2026-02-17     Mouse  Accessories     Mumbai        50    500
12        13 2026-01-13     Mouse  Accessories     Mumbai        50    500

    Revenue
0    500000
15   500000
46   500000
45   500000
41   500000
40   500000
36   500000
35   500000
31   500000
30   500000
26   500000
1    500000
21   500000
20   500000
16   500000
25   500000
5    500000
6    500000
11   500000
10   500000
14   180000
29   180000
44   180000
4    180000
39   180000
34   180000
9    180000
49   180000
24   180000
19   180000
28    45000
38    45000
48    45000
3     45000
18    45000
43    45000
13    45000
33    45000
23    45000
8     45000
37    25000
27    25000
22    25000
7     25000
42    25000
17    25000
32    25000
2     25000
47    25000
12    25000

section - 11 
 DATA CLEANING QUESTIONS

In [3]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Yash", "Babu", None, "Joel"],
    "Age": [20, np.nan, 22, 21],
    "Mark": [85, 70, np.nan, 90]
}

df = pd.DataFrame(data)

print(df.isnull())
print(df.isna())

    Name    Age   Mark
0  False  False  False
1  False   True  False
2   True  False   True
3  False  False  False
    Name    Age   Mark
0  False  False  False
1  False   True  False
2   True  False   True
3  False  False  False

In [4]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Mark"] = df["Mark"].fillna(df["Mark"].mean())

print(df)

   Name   Age       Mark
0  Yash  20.0  85.000000
1  Babu  21.0  70.000000
2  None  22.0  81.666667
3  Joel  21.0  90.000000

In [5]:
df["Name"] = df["Name"].fillna("Unknown")

print(df)

      Name   Age       Mark
0     Yash  20.0  85.000000
1     Babu  21.0  70.000000
2  Unknown  22.0  81.666667
3     Joel  21.0  90.000000

In [6]:
df = df.dropna()

print(df)

      Name   Age       Mark
0     Yash  20.0  85.000000
1     Babu  21.0  70.000000
2  Unknown  22.0  81.666667
3     Joel  21.0  90.000000

In [7]:
df = df.drop_duplicates()

print(df)

      Name   Age       Mark
0     Yash  20.0  85.000000
1     Babu  21.0  70.000000
2  Unknown  22.0  81.666667
3     Joel  21.0  90.000000

In [8]:
df.rename(columns={
    "Name": "Student_Name",
    "Mark": "Student_Mark"
}, inplace=True)

print(df)

  Student_Name   Age  Student_Mark
0         Yash  20.0     85.000000
1         Babu  21.0     70.000000
2      Unknown  22.0     81.666667
3         Joel  21.0     90.000000

In [9]:
df["Age"] = df["Age"].astype(int)

print(df)

  Student_Name  Age  Student_Mark
0         Yash   20     85.000000
1         Babu   21     70.000000
2      Unknown   22     81.666667
3         Joel   21     90.000000

In [12]:
df = df[df.duplicated()]
df

Empty DataFrame
Columns: [Student_Name, Age, Student_Mark]
Index: []

In [13]:
import pandas as pd

data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Yash", "Babu", "Keerthivasan", "Rinthiya", "Joel"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Experience": [3, 6, 8, 4, 7],
    "Salary": [45000, 55000, 75000, 48000, 65000]
}
df = pd.DataFrame(data)
df = df[df["Department"] == "IT"]
df

   Employee_ID          Name Department  Experience  Salary
0          101          Yash         IT           3   45000
2          103  Keerthivasan         IT           8   75000

In [16]:
import pandas as pd

data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Yash", "Babu", "Keerthivasan", "Rinthiya", "Joel"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Experience": [3, 6, 8, 4, 7],
    "Salary": [45000, 55000, 75000, 48000, 65000]
}
df = pd.DataFrame(data)
df = df[(df["Department"] == "IT") & (df["Salary"] > 50000)]
df

   Employee_ID          Name Department  Experience  Salary
2          103  Keerthivasan         IT           8   75000

In [19]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Yash", "Babu", None, "Joel"],
    "Age": [20, np.nan, 22, 21],
    "Mark": [85, 70, np.nan, 90]
}

df = pd.DataFrame(data)

df = df[df["Mark"].between(60, 80)]
df

   Name  Age  Mark
1  Babu  NaN  70.0

In [20]:
import pandas as pd

data = {
    "Order_ID": range(1, 51),
    "Date": pd.date_range("2026-01-01", periods=50),
    "Product": ["Laptop", "Phone", "Mouse", "Keyboard", "Monitor"] * 10,
    "Category": ["Electronics", "Electronics", "Accessories", "Accessories", "Electronics"] * 10,
    "City": ["Chennai", "Bangalore", "Mumbai", "Delhi", "Hyderabad"] * 10,
    "Quantity": [10, 20, 50, 30, 15] * 10,
    "Price": [50000, 25000, 500, 1500, 12000] * 10
}

df = pd.DataFrame(data)
df =  df[df["City"] == "Chennai"]
df

    Order_ID       Date Product     Category     City  Quantity  Price
0          1 2026-01-01  Laptop  Electronics  Chennai        10  50000
5          6 2026-01-06  Laptop  Electronics  Chennai        10  50000
10        11 2026-01-11  Laptop  Electronics  Chennai        10  50000
15        16 2026-01-16  Laptop  Electronics  Chennai        10  50000
20        21 2026-01-21  Laptop  Electronics  Chennai        10  50000
25        26 2026-01-26  Laptop  Electronics  Chennai        10  50000
30        31 2026-01-31  Laptop  Electronics  Chennai        10  50000
35        36 2026-02-05  Laptop  Electronics  Chennai        10  50000
40        41 2026-02-10  Laptop  Electronics  Chennai        10  50000
45        46 2026-02-15  Laptop  Electronics  Chennai        10  50000

In [24]:
import pandas as pd

data = {
    "Order_ID": range(1, 51),
    "Date": pd.date_range("2026-01-01", periods=50),
    "Product": ["Laptop", "Phone", "Mouse", "Keyboard", "Monitor"] * 10,
    "Category": ["Electronics", "Electronics", "Accessories", "Accessories", "Electronics"] * 10,
    "City": ["Chennai", "Bangalore", "Mumbai", "Delhi", "Hyderabad"] * 10,
    "Quantity": [10, 20, 50, 30, 15] * 10,
    "Price": [50000, 25000, 500, 1500, 12000] * 10
}

df = pd.DataFrame(data)
df = df[df["Quantity"] > 10]
df

    Order_ID       Date   Product     Category       City  Quantity  Price
1          2 2026-01-02     Phone  Electronics  Bangalore        20  25000
2          3 2026-01-03     Mouse  Accessories     Mumbai        50    500
3          4 2026-01-04  Keyboard  Accessories      Delhi        30   1500
4          5 2026-01-05   Monitor  Electronics  Hyderabad        15  12000
6          7 2026-01-07     Phone  Electronics  Bangalore        20  25000
7          8 2026-01-08     Mouse  Accessories     Mumbai        50    500
8          9 2026-01-09  Keyboard  Accessories      Delhi        30   1500
9         10 2026-01-10   Monitor  Electronics  Hyderabad        15  12000
11        12 2026-01-12     Phone  Electronics  Bangalore        20  25000
12        13 2026-01-13     Mouse  Accessories     Mumbai        50    500
13        14 2026-01-14  Keyboard  Accessories      Delhi        30   1500
14        15 2026-01-15   Monitor  Electronics  Hyderabad        15  12000
16        17 2026-01-17     Phone  Electronics  Bangalore        20  25000
17        18 2026-01-18     Mouse  Accessories     Mumbai        50    500
18        19 2026-01-19  Keyboard  Accessories      Delhi        30   1500
19        20 2026-01-20   Monitor  Electronics  Hyderabad        15  12000
21        22 2026-01-22     Phone  Electronics  Bangalore        20  25000
22        23 2026-01-23     Mouse  Accessories     Mumbai        50    500
23        24 2026-01-24  Keyboard  Accessories      Delhi        30   1500
24        25 2026-01-25   Monitor  Electronics  Hyderabad        15  12000
26        27 2026-01-27     Phone  Electronics  Bangalore        20  25000
27        28 2026-01-28     Mouse  Accessories     Mumbai        50    500
28        29 2026-01-29  Keyboard  Accessories      Delhi        30   1500
29        30 2026-01-30   Monitor  Electronics  Hyderabad        15  12000
31        32 2026-02-01     Phone  Electronics  Bangalore        20  25000
32        33 2026-02-02     Mouse  Accessories     Mumbai        50    500
33        34 2026-02-03  Keyboard  Accessories      Delhi        30   1500
34        35 2026-02-04   Monitor  Electronics  Hyderabad        15  12000
36        37 2026-02-06     Phone  Electronics  Bangalore        20  25000
37        38 2026-02-07     Mouse  Accessories     Mumbai        50    500
38        39 2026-02-08  Keyboard  Accessories      Delhi        30   1500
39        40 2026-02-09   Monitor  Electronics  Hyderabad        15  12000
41        42 2026-02-11     Phone  Electronics  Bangalore        20  25000
42        43 2026-02-12     Mouse  Accessories     Mumbai        50    500
43        44 2026-02-13  Keyboard  Accessories      Delhi        30   1500
44        45 2026-02-14   Monitor  Electronics  Hyderabad        15  12000
46        47 2026-02-16     Phone  Electronics  Bangalore        20  25000
47        48 2026-02-17     Mouse  Accessories     Mumbai        50    500
48        49 2026-02-18  Keyboard  Accessories      Delhi        30   1500
49        50 2026-02-19   Monitor  Electronics  Hyderabad        15  12000

In [25]:
import pandas as pd

data = {
    "Order_ID": range(1, 51),
    "Date": pd.date_range("2026-01-01", periods=50),
    "Product": ["Laptop", "Phone", "Mouse", "Keyboard", "Monitor"] * 10,
    "Category": ["Electronics", "Electronics", "Accessories", "Accessories", "Electronics"] * 10,
    "City": ["Chennai", "Bangalore", "Mumbai", "Delhi", "Hyderabad"] * 10,
    "Quantity": [10, 20, 50, 30, 15] * 10,
    "Price": [50000, 25000, 500, 1500, 12000] * 10
}

df = pd.DataFrame(data)
df = df[df["Price"].between(1000, 10000)]
df

    Order_ID       Date   Product     Category   City  Quantity  Price
3          4 2026-01-04  Keyboard  Accessories  Delhi        30   1500
8          9 2026-01-09  Keyboard  Accessories  Delhi        30   1500
13        14 2026-01-14  Keyboard  Accessories  Delhi        30   1500
18        19 2026-01-19  Keyboard  Accessories  Delhi        30   1500
23        24 2026-01-24  Keyboard  Accessories  Delhi        30   1500
28        29 2026-01-29  Keyboard  Accessories  Delhi        30   1500
33        34 2026-02-03  Keyboard  Accessories  Delhi        30   1500
38        39 2026-02-08  Keyboard  Accessories  Delhi        30   1500
43        44 2026-02-13  Keyboard  Accessories  Delhi        30   1500
48        49 2026-02-18  Keyboard  Accessories  Delhi        30   1500

In [26]:
import pandas as pd

data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Yash", "Babu", "Keerthivasan", "Rinthiya", "Joel"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Experience": [3, 6, 8, 4, 7],
    "Salary": [45000, 55000, 75000, 48000, 65000]
}
df = pd.DataFrame(data)
df = df.groupby("Department")["Salary"].agg(
    ["count", "mean", "max", "min"]
)
df

            count     mean    max    min
Department
Finance         1  48000.0  48000  48000
HR              2  60000.0  65000  55000
IT              2  60000.0  75000  45000

In [32]:
data = {
    "Order_ID": range(1, 51),
    "Date": pd.date_range("2026-01-01", periods=50),
    "Product": ["Laptop", "Phone", "Mouse", "Keyboard", "Monitor"] * 10,
    "Category": ["Electronics", "Electronics", "Accessories", "Accessories", "Electronics"] * 10,
    "City": ["Chennai", "Bangalore", "Mumbai", "Delhi", "Hyderabad"] * 10,
    "Quantity": [10, 20, 50, 30, 15] * 10,
    "Price": [50000, 25000, 500, 1500, 12000] * 10
}

df = pd.DataFrame(data)
df["Revenue"] = df["Quantity"] * df["Price"]

result = df.groupby("Category").agg({
    "Quantity": "sum",
    "Revenue": "sum",
    "Price": "mean"
})

print(result)

             Quantity   Revenue    Price
Category
Accessories       800    700000   1000.0
Electronics       450  11800000  29000.0

In [36]:
data = {
    "Name": ["Yash", "Babu", "Keerthi", "Joel"],
    "Age": [20, 21, 22, 21],
    "Course": ["Python", "Java", "Python", "Java"],
    "Mark": [85, 70, 90, 60]
}

df = pd.DataFrame(data)

df = df.groupby("Course")["Mark"].agg(
    ["count", "mean", "max", "min"]
)

df

        count  mean  max  min
Course
Java        2  65.0   70   60
Python      2  87.5   90   85

SECTION 14 - NUMPY + PANDAS COMBINED

In [39]:
import numpy as np
import pandas as pd

names = np.array([
    "Yash", "Babu", "Keerthi", "Joel", "Arun",
    "Ravi", "Ram", "Kumar", "Priya", "Divya"
])

marks = np.array([85, 70, 90, 65, 78, 88, 55, 92, 74, 81])

df = pd.DataFrame({
    "Name": names,
    "Mark": marks
})
df

      Name  Mark
0     Yash    85
1     Babu    70
2  Keerthi    90
3     Joel    65
4     Arun    78
5     Ravi    88
6      Ram    55
7    Kumar    92
8    Priya    74
9    Divya    81

In [38]:
import numpy as np
import pandas as pd

data = {
    "Python": [80, 70, 90, 60],
    "Java": [75, 65, 85, 70],
    "SQL": [90, 80, 95, 75]
}

df = pd.DataFrame(data)

df["Total"] = np.sum(df[["Python", "Java", "SQL"]], axis=1)

df

   Python  Java  SQL  Total
0      80    75   90    245
1      70    65   80    215
2      90    85   95    270
3      60    70   75    205

In [45]:
import numpy as np
import pandas as pd

data = {
    "Python": [80, 70, 90, 60],
    "Java": [75, 65, 85, 70],
    "SQL": [90, 80, 95, 75]
}

df = pd.DataFrame(data)

df["Total"] = np.sum(df[["Python", "Java", "SQL"]], axis=1)

df["Result"] = np.where(
    df["Total"] >= 150,
    "PASS",
    "FAIL"
)
df

   Python  Java  SQL  Total Result
0      80    75   90    245   PASS
1      70    65   80    215   PASS
2      90    85   95    270   PASS
3      60    70   75    205   PASS

In [46]:
import numpy as np
import pandas as pd

data = {
    "Mark": [80, 45, 90, 35, 70]
}

df = pd.DataFrame(data)

df["Result"] = np.where(
    df["Mark"] >= 50,
    "PASS",
    "FAIL"
)
df

   Mark Result
0    80   PASS
1    45   FAIL
2    90   PASS
3    35   FAIL
4    70   PASS

In [47]:
import numpy as np
import pandas as pd

data = {
    "Name": ["Yash", "Babu", "Keerthi", "Joel"],
    "Salary": [40000, 50000, 60000, 70000]
}

df = pd.DataFrame(data)

df["New_Salary"] = np.multiply(df["Salary"], 1.10)
df

      Name  Salary  New_Salary
0     Yash   40000     44000.0
1     Babu   50000     55000.0
2  Keerthi   60000     66000.0
3     Joel   70000     77000.0

In [51]:
import numpy as np
import pandas as pd

data = {
    "Product": ["A", "B", "C", "D", "E"],
    "Quantity": np.random.randint(1, 20, 5),
    "Price": np.random.randint(100, 1000, 5)
}

df = pd.DataFrame(data)

df["Sales"] = df["Quantity"] * df["Price"]

print(df)
print(df["Sales"].sum())
print( df["Sales"].mean())
print( df["Sales"].max())

  Product  Quantity  Price  Sales
0       A        10    984   9840
1       B        17    606  10302
2       C        13    880  11440
3       D         6    836   5016
4       E         9    376   3384
39982
7996.4
11440

In [55]:
import numpy as np
import pandas as pd

marks = np.random.randint(0, 101, 100)

df = pd.DataFrame({
    "Mark": marks
})

print( df["Mark"].mean())
print( df["Mark"].median())
print(df["Mark"].max())
print(df["Mark"].min())

pass_percentage = (df["Mark"] >= 50).mean() * 100

print( pass_percentage)

50.27
48.0
98
1
48.0

 SECTION 15 - FINAL MINI PROJECT

Student Management Analysis System

In [1]:
import numpy as np 
import pandas as pd 

data = {
    "Name": ["Yash", "Babu", "Keerthi", "Joel", "Yash"],
    "Course": ["Python", "Java", "Python", "Java", "Python"],
    "Python": [85, 70, 90, 65, 85],
    "Java": [80, 75, 88, 60, 80],
    "SQL": [90, 68, 95, np.nan, 90]
}

df = pd.DataFrame(data)

New_Student={
    "Name":"Ravi",
    "Course":"Python",
    "Python": 75,
    "Java": 88,
    "SQL": 90

}
df.loc[len(df)] = New_Student
df

subjects = ["Python","Java","SQL"]
df["Total"]=np.sum(df[subjects], axis = 1)


df["Average"] = np.mean(df[subjects], axis = 1)


df["Grade"] = np.where(df["Average"]>80,"A", 
                       np.where (df["Average"]>60,"B",
                       np.where(df["Average"]> 50,"C","D")  
                                       ))

df


df["Result"] = np.where(
                       (df[subjects]>=50).all (axis =1),"Pass","Fail")

print("\n Top student:")
print(df.loc [df["Total"].idxmax()])

print("Bottom Student:")
print(df.loc[df["Total"].idxmin()])

print("\n Search name:")
print(df[df["Name"]=="Yash"])

print("\n Python_students:")
print(df[df["Course"] == "Python"])

df = df.sort_values('Total',ascending=False)
df

df = df.drop_duplicates() 

df["SQL"]=df["SQL"].fillna(df["SQL"].mean())
df

 Top student:
Name       Keerthi
Course      Python
Python          90
Java            88
SQL           95.0
Total        273.0
Average       91.0
Grade            A
Result        Pass
Name: 2, dtype: object
Bottom Student:
Name        Joel
Course      Java
Python        65
Java          60
SQL          NaN
Total      125.0
Average     62.5
Grade          B
Result      Fail
Name: 3, dtype: object

 Search name:
   Name  Course  Python  Java   SQL  Total  Average Grade Result
0  Yash  Python      85    80  90.0  255.0     85.0     A   Pass
4  Yash  Python      85    80  90.0  255.0     85.0     A   Pass

 Python_students:
      Name  Course  Python  Java   SQL  Total    Average Grade Result
0     Yash  Python      85    80  90.0  255.0  85.000000     A   Pass
2  Keerthi  Python      90    88  95.0  273.0  91.000000     A   Pass
4     Yash  Python      85    80  90.0  255.0  85.000000     A   Pass
5     Ravi  Python      75    88  90.0  253.0  84.333333     A   Pass

      Name  Course  Python  Java    SQL  Total    Average Grade Result
2  Keerthi  Python      90    88  95.00  273.0  91.000000     A   Pass
0     Yash  Python      85    80  90.00  255.0  85.000000     A   Pass
5     Ravi  Python      75    88  90.00  253.0  84.333333     A   Pass
1     Babu    Java      70    75  68.00  213.0  71.000000     B   Pass
3     Joel    Java      65    60  85.75  125.0  62.500000     B   Fail

 SECTION 16 - FINAL REAL-TIME PROJECT

Sales Management System

In [2]:
import numpy as np
import pandas as pd

data = {
    "Order_ID": range(1, 11),
    "Product": ["Rice", "Oil", "Milk", "Soap", "Rice",
                "Oil", "Bread", "Milk", "Soap", "Bread"],
    "Category": ["Grocery", "Grocery", "Dairy", "Personal",
                 "Grocery", "Grocery", "Bakery", "Dairy",
                 "Personal", "Bakery"],
    "City": ["Chennai", "Delhi", "Chennai", "Mumbai", "Delhi",
             "Chennai", "Mumbai", "Delhi", "Chennai", "Mumbai"],
    "Quantity": [10, 5, 20, 15, 8, 6, 12, 18, 10, 14],
    "Price": [1200, 1800, 60, 50, 1200, 1800, 40, 60, 50, 40]
}

df = pd.DataFrame(data)


print(df)


print("Total Quantity:", df["Quantity"].sum())
print("Average Price:", df["Price"].mean())

df["Revenue"] = df["Quantity"] * df["Price"]

print("Total Revenue:", df["Revenue"].sum())
print("Average Revenue:", df["Revenue"].mean())

print("Highest Sale:")
print(df.loc[df["Revenue"].idxmax()])

print("Lowest Sale:")
print(df.loc[df["Revenue"].idxmin()])


best = df.groupby("Product")["Quantity"].sum().idxmax()
print("Best Selling Product:", best)


print(df.groupby("Category")["Revenue"].sum())


print(df.groupby("City")["Revenue"].sum())


product_revenue = df.groupby("Product")["Revenue"].sum()
print(product_revenue)

print(product_revenue.nlargest(5))

print(df.nlargest(10, "Revenue"))

df["Quantity"] = df["Quantity"].fillna(df["Quantity"].mean())
df["Price"] = df["Price"].fillna(df["Price"].mean())


df = df.drop_duplicates()


df = df.sort_values("Revenue", ascending=False)


df.to_csv("supermarket_sales_report.csv", index=False)


print("\nFinal Sales Summary")
print("Total Revenue:", df["Revenue"].sum())
print("Average Revenue:", df["Revenue"].mean())
print("Best Product:", df.groupby("Product")["Quantity"].sum().idxmax())
print("Highest Revenue City:", df.groupby("City")["Revenue"].sum().idxmax())

print("\nFinal Report:")
print(df)

   Order_ID Product  Category     City  Quantity  Price
0         1    Rice   Grocery  Chennai        10   1200
1         2     Oil   Grocery    Delhi         5   1800
2         3    Milk     Dairy  Chennai        20     60
3         4    Soap  Personal   Mumbai        15     50
4         5    Rice   Grocery    Delhi         8   1200
5         6     Oil   Grocery  Chennai         6   1800
6         7   Bread    Bakery   Mumbai        12     40
7         8    Milk     Dairy    Delhi        18     60
8         9    Soap  Personal  Chennai        10     50
9        10   Bread    Bakery   Mumbai        14     40
Total Quantity: 118
Average Price: 630.0
Total Revenue: 45970
Average Revenue: 4597.0
Highest Sale:
Order_ID          1
Product        Rice
Category    Grocery
City        Chennai
Quantity         10
Price          1200
Revenue       12000
Name: 0, dtype: object
Lowest Sale:
Order_ID         7
Product      Bread
Category    Bakery
City        Mumbai
Quantity        12
Price           40
Revenue        480
Name: 6, dtype: object
Best Selling Product: Milk
Category
Bakery       1040
Dairy        2280
Grocery     41400
Personal     1250
Name: Revenue, dtype: int64
City
Chennai    24500
Delhi      19680
Mumbai      1790
Name: Revenue, dtype: int64
Product
Bread     1040
Milk      2280
Oil      19800
Rice     21600
Soap      1250
Name: Revenue, dtype: int64
Product
Rice     21600
Oil      19800
Milk      2280
Soap      1250
Bread     1040
Name: Revenue, dtype: int64
   Order_ID Product  Category     City  Quantity  Price  Revenue
0         1    Rice   Grocery  Chennai        10   1200    12000
5         6     Oil   Grocery  Chennai         6   1800    10800
4         5    Rice   Grocery    Delhi         8   1200     9600
1         2     Oil   Grocery    Delhi         5   1800     9000
2         3    Milk     Dairy  Chennai        20     60     1200
7         8    Milk     Dairy    Delhi        18     60     1080
3         4    Soap  Personal   Mumbai        15     50      750
9        10   Bread    Bakery   Mumbai        14     40      560
8         9    Soap  Personal  Chennai        10     50      500
6         7   Bread    Bakery   Mumbai        12     40      480

Final Sales Summary
Total Revenue: 45970
Average Revenue: 4597.0
Best Product: Milk
Highest Revenue City: Chennai

Final Report:
   Order_ID Product  Category     City  Quantity  Price  Revenue
0         1    Rice   Grocery  Chennai        10   1200    12000
5         6     Oil   Grocery  Chennai         6   1800    10800
4         5    Rice   Grocery    Delhi         8   1200     9600
1         2     Oil   Grocery    Delhi         5   1800     9000
2         3    Milk     Dairy  Chennai        20     60     1200
7         8    Milk     Dairy    Delhi        18     60     1080
3         4    Soap  Personal   Mumbai        15     50      750
9        10   Bread    Bakery   Mumbai        14     40      560
8         9    Soap  Personal  Chennai        10     50      500
6         7   Bread    Bakery   Mumbai        12     40      480